apiVersion: v1
kind: Service
metadata:
  name: starbucks-service
spec:
  selector: 
    app: starbucksapp
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type: LoadBalancer
    
