# CICD using GitOps Actions

name: CI/CD

#Exclude the workflow to run on changes on helm chart
on: 
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'
      - 'starbucks-chart'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Nodejs
      uses: actions/set-node@v4
      with:
        node-version: 20